# Generated by Django 5.0.6 on 2026-07-23 10:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.UUIDField()),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('focus_area', models.CharField(blank=True, default='', max_length=100)),
                ('total_rounds', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveSmallIntegerField(help_text="1-indexed position of this question within the session's rounds")),
                ('text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('question_type', models.CharField(choices=[('open_ended', 'Open ended'), ('multiple_choice', 'Multiple choice')], default='open_ended', max_length=20)),
                ('options', models.JSONField(blank=True, default=None, null=True)),
                ('correct_option', models.PositiveSmallIntegerField(blank=True, default=None, help_text='Index into `options`. Never serialize this to the frontend before the answer is submitted.', null=True)),
                ('time_limit', models.PositiveIntegerField(help_text='Seconds allowed to answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='prep.interviewsession')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, default='')),
                ('selected_option', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time_taken', models.PositiveIntegerField(help_text='Seconds the candidate took')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=10)),
                ('score', models.FloatField(blank=True, null=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('suggested_answer', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='prep.question')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('session', 'round_number'), name='unique_round_per_session'),
        ),
    ]
