# Generated by Django 5.0.6 on 2026-07-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='user_id',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000000'),
            preserve_default=False,
        ),
    ]
