# Generated by Django 5.0.6 on 2026-07-23 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('needs_review', 'Needs review'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.IntegerField()),
                ('completeness', models.IntegerField()),
                ('keyword_relevance', models.IntegerField()),
                ('clarity', models.IntegerField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='parser.cv')),
            ],
        ),
        migrations.CreateModel(
            name='CVSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('missing_keyword', 'Missing keyword'), ('weak_bullet', 'Weak bullet'), ('unquantified', 'Unquantified achievement')], max_length=30)),
                ('field_reference', models.CharField(max_length=100)),
                ('suggestion_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('edited', 'Edited')], default='pending', max_length=20)),
                ('edited_text', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='parser.cv')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('professional_summary', models.TextField(blank=True, null=True)),
                ('education', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('parser_version', models.CharField(default='v1', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('flagged_sections', models.JSONField(blank=True, default=list)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed', to='parser.cv')),
            ],
        ),
        migrations.CreateModel(
            name='ParseFailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=100)),
                ('error_detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_logs', to='parser.cv')),
            ],
        ),
    ]
