# Generated by Django 5.0.6 on 2026-07-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvsuggestion',
            name='previous_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cvsuggestion',
            name='previous_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
