# Generated by Django 5.0.6 on 2026-07-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_cvsuggestion_previous_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedcv',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parsedcv',
            name='role_category',
            field=models.CharField(default='unspecified', max_length=100),
        ),
    ]
