# Generated by Django 5.0.6 on 2026-08-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_parsedcv_experience_years_parsedcv_role_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsuggestion',
            name='field_reference',
            field=models.CharField(max_length=255),
        ),
    ]
