# Generated by Django 5.0.6 on 2026-07-23 08:03

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('cv_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('skill_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, help_text='Canonical Skill IDs, already resolved. Never raw skill strings.', size=None)),
                ('experience_years', models.FloatField()),
                ('seniority', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=10)),
                ('role_category', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cv',
                'indexes': [models.Index(fields=['role_category'], name='cv_role_ca_73a55a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('skill_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), default=list, help_text='Canonical Skill IDs, already resolved. Single list', size=None)),
                ('seniority_level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=10)),
                ('role_category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('source_url', models.URLField(help_text='Direct link to the original listing', max_length=500)),
                ('ingested_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'job',
                'indexes': [models.Index(fields=['role_category'], name='job_role_ca_3fe149_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias_name', models.CharField(max_length=100, unique=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='matching.skill')),
            ],
            options={
                'db_table': 'skill_alias',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.PositiveSmallIntegerField()),
                ('breakdown', models.JSONField()),
                ('computed_at', models.DateField(auto_now=True)),
                ('cv', models.ForeignKey(db_column='cv_id', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matching.cv')),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matching.job')),
            ],
            options={
                'db_table': 'match',
                'indexes': [models.Index(fields=['cv', '-overall_score'], name='match_cv_id_f90cf8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('cv', 'job'), name='unique_cv_job_match'),
        ),
    ]
