# Generated by Django 5.0.6 on 2026-07-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='min_experience',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
